/*
 * Copyright 2026 Rajnish Kumar
 * SPDX-License-Identifier: Apache-2.0
 */
package rajnishkmehta.sakshi.portal.debug

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp
import androidx.core.content.FileProvider
import rajnishkmehta.sakshi.portal.ui.theme.PortalTheme
import java.io.File

/**
 * An activity specifically for debug builds that allows developers to view, export, and clear
 * logs generated by the [DebugLogger].
 *
 * Uses the Material 3 design system to integrate with the main app's theme and supports dynamic colors.
 */
class DebugLogsActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContent {
            PortalTheme {
                DebugLogsScreen(
                    onBack = { finish() },
                    onExport = { file -> exportLogFile(file) }
                )
            }
        }
    }

    private fun exportLogFile(fileToExport: File) {
        if (fileToExport.exists() && fileToExport.length() > 0) {
            val uri = FileProvider.getUriForFile(
                this,
                "${applicationContext.packageName}.debug.provider",
                fileToExport
            )

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            startActivity(Intent.createChooser(intent, "Share Log File"))
        } else {
            Toast.makeText(this, "Log file is empty or does not exist", Toast.LENGTH_SHORT).show()
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DebugLogsScreen(
    onBack: () -> Unit,
    onExport: (File) -> Unit
) {
    var files by remember { mutableStateOf(DebugLogger.getLogFiles().sortedBy { it.name }) }
    val context = LocalContext.current

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Debug Logs") },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(painter = painterResource(id = android.R.drawable.ic_menu_revert), contentDescription = "Back")
                    }
                }
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .padding(16.dp)
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Button(
                    onClick = {
                        val success = DebugLogger.clearLogs()
                        if (success) {
                            Toast.makeText(context, "Logs cleared", Toast.LENGTH_SHORT).show()
                        }
                        files = DebugLogger.getLogFiles().sortedBy { it.name }
                    },
                    modifier = Modifier.weight(1f)
                ) {
                    Text("Clear Active Logs")
                }

                Button(
                    onClick = {
                        val allFiles = DebugLogger.getLogFiles()
                        val rotatedPattern = Regex(".*_\\d+\\.txt$")
                        var anyDeleted = false
                        for (file in allFiles) {
                            if (rotatedPattern.matches(file.name)) {
                                if (file.delete()) {
                                    anyDeleted = true
                                }
                            }
                        }
                        if (anyDeleted) {
                            Toast.makeText(context, "Rotated logs deleted", Toast.LENGTH_SHORT).show()
                            files = DebugLogger.getLogFiles().sortedBy { it.name }
                        }
                    },
                    modifier = Modifier.weight(1f)
                ) {
                    Text("Delete Rotated")
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            val rotatedPattern = Regex(".*_\\d+\\.txt$")
            val activeFiles = files.filter { !rotatedPattern.matches(it.name) }
            val rotatedFiles = files.filter { rotatedPattern.matches(it.name) }

            LazyColumn(
                modifier = Modifier.fillMaxSize(),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                if (activeFiles.isNotEmpty()) {
                    item {
                        Text(
                            text = "Active Logs",
                            style = MaterialTheme.typography.titleMedium,
                            color = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.padding(vertical = 8.dp)
                        )
                    }
                    items(activeFiles) { file ->
                        LogFileRow(
                            file = file,
                            onExport = { onExport(file) },
                            onDelete = {
                                if (file.delete()) {
                                    Toast.makeText(context, "Deleted ${file.name}", Toast.LENGTH_SHORT).show()
                                    files = DebugLogger.getLogFiles().sortedBy { it.name }
                                }
                            }
                        )
                    }
                }

                if (rotatedFiles.isNotEmpty()) {
                    item {
                        Text(
                            text = "Rotated Logs",
                            style = MaterialTheme.typography.titleMedium,
                            color = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.padding(vertical = 8.dp)
                        )
                    }
                    items(rotatedFiles) { file ->
                        LogFileRow(
                            file = file,
                            onExport = { onExport(file) },
                            onDelete = {
                                if (file.delete()) {
                                    Toast.makeText(context, "Deleted ${file.name}", Toast.LENGTH_SHORT).show()
                                    files = DebugLogger.getLogFiles().sortedBy { it.name }
                                }
                            }
                        )
                    }
                }
            }
        }
    }
}

@Composable
fun LogFileRow(
    file: File,
    onExport: () -> Unit,
    onDelete: () -> Unit
) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Column(modifier = Modifier.weight(1f)) {
            Text(text = file.name, style = MaterialTheme.typography.bodyLarge)
            val length = file.length()
            Text(text = if (length < 1024) "$length Bytes" else "${length / 1024} KB", style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }

        IconButton(onClick = onExport) {
            Icon(painter = painterResource(id = android.R.drawable.ic_menu_share), contentDescription = "Share")
        }

        IconButton(onClick = onDelete) {
            Icon(painter = painterResource(id = android.R.drawable.ic_menu_delete), contentDescription = "Delete")
        }
    }
}
