/*
 * Copyright 2026 Rajnish Kumar
 * SPDX-License-Identifier: Apache-2.0
 */
package rajnishkmehta.sakshi.portal.debug

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.graphics.vector.rememberVectorPainter
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp
import androidx.core.content.FileProvider
import java.io.File
import rajnishkmehta.sakshi.portal.R

/**
 * An activity specifically for debug builds that allows developers to view, export, and clear
 * logs generated by the [DebugLogger].
 */
class DebugLogsActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    DebugLogsScreen(
                        onBackClick = { finish() },
                        onExportClick = { file -> exportLogFile(file) }
                    )
                }
            }
        }
    }

    private fun exportLogFile(fileToExport: File) {
        if (fileToExport.exists() && fileToExport.length() > 0) {
            val uri = FileProvider.getUriForFile(
                this,
                "${applicationContext.packageName}.debug.provider",
                fileToExport
            )

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            startActivity(Intent.createChooser(intent, "Share Log File"))
        } else {
            Toast.makeText(this, "Log file is empty or does not exist", Toast.LENGTH_SHORT).show()
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DebugLogsScreen(
    onBackClick: () -> Unit,
    onExportClick: (File) -> Unit
) {
    val context = LocalContext.current
    var logFiles by remember { mutableStateOf(DebugLogger.getLogFiles().sortedBy { it.name }) }

    val activeFiles = logFiles.filter { !it.name.matches(Regex(".*_\\d+\\.txt$")) }
    val rotatedFiles = logFiles.filter { it.name.matches(Regex(".*_\\d+\\.txt$")) }

    fun refreshLogs() {
        logFiles = DebugLogger.getLogFiles().sortedBy { it.name }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Debug Logs") },
                navigationIcon = {
                    IconButton(onClick = onBackClick) {
                        Icon(painter = painterResource(id = android.R.drawable.ic_menu_revert), contentDescription = "Back")
                    }
                }
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .padding(paddingValues)
                .fillMaxSize()
                .padding(16.dp)
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Button(onClick = {
                    if (DebugLogger.clearLogs()) {
                        Toast.makeText(context, "Logs cleared", Toast.LENGTH_SHORT).show()
                    }
                    refreshLogs()
                }) {
                    Text("Clear Logs")
                }

                Button(onClick = {
                    var anyDeleted = false
                    for (file in rotatedFiles) {
                        if (file.delete()) {
                            anyDeleted = true
                        }
                    }
                    if (anyDeleted) {
                        Toast.makeText(context, "Rotated logs deleted", Toast.LENGTH_SHORT).show()
                        refreshLogs()
                    }
                }) {
                    Text("Delete Rotated")
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            LazyColumn(modifier = Modifier.fillMaxSize()) {
                if (activeFiles.isNotEmpty()) {
                    item {
                        Text("Active Logs", style = MaterialTheme.typography.titleMedium, modifier = Modifier.padding(vertical = 8.dp))
                    }
                    items(activeFiles) { file ->
                        LogFileRow(file, onExportClick, onDeleteClick = {
                            if (file.delete()) {
                                Toast.makeText(context, "Deleted ${file.name}", Toast.LENGTH_SHORT).show()
                                refreshLogs()
                            }
                        })
                    }
                }

                if (rotatedFiles.isNotEmpty()) {
                    item {
                        Spacer(modifier = Modifier.height(16.dp))
                        Text("Rotated Logs", style = MaterialTheme.typography.titleMedium, modifier = Modifier.padding(vertical = 8.dp))
                    }
                    items(rotatedFiles) { file ->
                        LogFileRow(file, onExportClick, onDeleteClick = {
                            if (file.delete()) {
                                Toast.makeText(context, "Deleted ${file.name}", Toast.LENGTH_SHORT).show()
                                refreshLogs()
                            }
                        })
                    }
                }
            }
        }
    }
}

@Composable
fun LogFileRow(
    file: File,
    onExportClick: (File) -> Unit,
    onDeleteClick: () -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 8.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Column(modifier = Modifier.weight(1f)) {
            Text(file.name, style = MaterialTheme.typography.bodyLarge)
            Text("${file.length() / 1024} KB", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
        IconButton(onClick = { onExportClick(file) }) {
            Icon(painter = painterResource(id = android.R.drawable.ic_menu_share), contentDescription = "Export")
        }
        IconButton(onClick = onDeleteClick) {
            Icon(painter = painterResource(id = android.R.drawable.ic_menu_delete), contentDescription = "Delete")
        }
    }
}
