package rajnishkmehta.sakshi.camera.debug

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.FileProvider
import com.google.android.material.appbar.MaterialToolbar
import com.google.android.material.button.MaterialButton
import com.google.android.material.color.DynamicColors
import rajnishkmehta.sakshi.camera.R

/**
 * An activity specifically for debug builds that allows developers to view, export, and clear
 * logs generated by the [DebugLogger].
 *
 * Uses the Material 3 design system to integrate with the main app's theme and supports dynamic colors.
 */
class DebugLogsActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        DynamicColors.applyToActivityIfAvailable(this)
        setContentView(R.layout.activity_debug_logs)

        val toolbar = findViewById<MaterialToolbar>(R.id.toolbar)
        toolbar.setNavigationOnClickListener { finish() }

        findViewById<MaterialButton>(R.id.exportAllLogsBtn).setOnClickListener {
            exportLogFile("all_logs.txt")
        }

        findViewById<MaterialButton>(R.id.exportErrorLogsBtn).setOnClickListener {
            exportLogFile("error_logs.txt")
        }

        findViewById<MaterialButton>(R.id.exportWarningLogsBtn).setOnClickListener {
            exportLogFile("warning_logs.txt")
        }

        findViewById<MaterialButton>(R.id.exportInfoLogsBtn).setOnClickListener {
            exportLogFile("info_logs.txt")
        }

        findViewById<MaterialButton>(R.id.clearLogsBtn).setOnClickListener {
            DebugLogger.clearLogs()
            Toast.makeText(this, "Logs cleared", Toast.LENGTH_SHORT).show()
        }
    }

    /**
     * Finds the requested log file and opens an Android share sheet using a secure [FileProvider].
     *
     * @param fileName The name of the text file inside the debug logs directory to export.
     */
    private fun exportLogFile(fileName: String) {
        val files = DebugLogger.getLogFiles()
        val fileToExport = files.find { it.name == fileName }

        if (fileToExport != null && fileToExport.exists() && fileToExport.length() > 0) {
            val uri = FileProvider.getUriForFile(
                this,
                "${applicationContext.packageName}.debug.provider",
                fileToExport
            )

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            startActivity(Intent.createChooser(intent, "Share Log File"))
        } else {
            Toast.makeText(this, "Log file is empty or does not exist", Toast.LENGTH_SHORT).show()
        }
    }
}
