/*
 * Copyright 2026 Rajnish Kumar
 * SPDX-License-Identifier: Apache-2.0
 */
package rajnishkmehta.sakshi.camera.debug

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.FileProvider
import com.google.android.material.appbar.MaterialToolbar
import com.google.android.material.button.MaterialButton
import com.google.android.material.color.DynamicColors
import rajnishkmehta.sakshi.camera.R
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.ImageButton
import android.view.Gravity
import java.io.File

/**
 * An activity specifically for debug builds that allows developers to view, export, and clear
 * logs generated by the [DebugLogger].
 *
 * Uses the Material 3 design system to integrate with the main app's theme and supports dynamic colors.
 */
class DebugLogsActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        DynamicColors.applyToActivityIfAvailable(this)
        setContentView(R.layout.activity_debug_logs)

        val toolbar = findViewById<MaterialToolbar>(R.id.toolbar)
        toolbar.setNavigationOnClickListener { finish() }

        findViewById<MaterialButton>(R.id.clearLogsBtn).setOnClickListener {
            val success = DebugLogger.clearLogs()
            if (success) {
                Toast.makeText(this, "Logs cleared", Toast.LENGTH_SHORT).show()
            }
            populateLogFilesList()
        }

        findViewById<MaterialButton>(R.id.deleteRotatedLogsBtn).setOnClickListener {
            val files = DebugLogger.getLogFiles()
            val rotatedPattern = Regex(".*_\\d+\\.txt$")
            var anyDeleted = false
            for (file in files) {
                if (rotatedPattern.matches(file.name)) {
                    if (file.delete()) {
                        anyDeleted = true
                    }
                }
            }
            if (anyDeleted) {
                Toast.makeText(this, "Rotated logs deleted", Toast.LENGTH_SHORT).show()
                populateLogFilesList()
            }
        }

        populateLogFilesList()
    }

    private fun populateLogFilesList() {
        val activeContainer = findViewById<LinearLayout>(R.id.activeLogFilesContainer)
        val rotatedContainer = findViewById<LinearLayout>(R.id.rotatedLogFilesContainer)
        activeContainer.removeAllViews()
        rotatedContainer.removeAllViews()

        val files = DebugLogger.getLogFiles().sortedBy { it.name }
        val rotatedPattern = Regex(".*_\\d+\\.txt$")

        // Resolve primary text color using Material3 theme attribute
        val typedValue = android.util.TypedValue()
        theme.resolveAttribute(android.R.attr.textColorPrimary, typedValue, true)
        val primaryTextColor = if (typedValue.type >= android.util.TypedValue.TYPE_FIRST_COLOR_INT && typedValue.type <= android.util.TypedValue.TYPE_LAST_COLOR_INT) {
            typedValue.data
        } else {
            androidx.core.content.ContextCompat.getColor(this, typedValue.resourceId)
        }

        for (file in files) {
            val row = LinearLayout(this).apply {
                orientation = LinearLayout.HORIZONTAL
                layoutParams = LinearLayout.LayoutParams(
                    LinearLayout.LayoutParams.MATCH_PARENT,
                    LinearLayout.LayoutParams.WRAP_CONTENT
                ).apply {
                    setMargins(0, 0, 0, 16)
                }
                gravity = Gravity.CENTER_VERTICAL
            }

            val textLayout = LinearLayout(this).apply {
                orientation = LinearLayout.VERTICAL
                layoutParams = LinearLayout.LayoutParams(
                    0,
                    LinearLayout.LayoutParams.WRAP_CONTENT,
                    1.0f
                )
            }

            val nameView = TextView(this).apply {
                text = file.name
                textSize = 16f
                setTextColor(primaryTextColor)
            }

            val sizeView = TextView(this).apply {
                val sizeKb = file.length() / 1024
                text = "${sizeKb} KB"
                textSize = 12f
                setTextColor(primaryTextColor)
            }

            textLayout.addView(nameView)
            textLayout.addView(sizeView)

            val exportBtn = ImageButton(this).apply {
                setImageResource(android.R.drawable.ic_menu_share)
                background = null
                setOnClickListener {
                    exportLogFile(file)
                }
            }

            val deleteBtn = ImageButton(this).apply {
                setImageResource(android.R.drawable.ic_menu_delete)
                background = null
                setOnClickListener {
                    if (file.delete()) {
                        Toast.makeText(this@DebugLogsActivity, "Deleted ${file.name}", Toast.LENGTH_SHORT).show()
                        populateLogFilesList()
                    }
                }
            }

            row.addView(textLayout)
            row.addView(exportBtn)
            row.addView(deleteBtn)

            if (rotatedPattern.matches(file.name)) {
                rotatedContainer.addView(row)
            } else {
                activeContainer.addView(row)
            }
        }
    }

    /**
     * Finds the requested log file and opens an Android share sheet using a secure [FileProvider].
     *
     * @param fileName The name of the text file inside the debug logs directory to export.
     */
    private fun exportLogFile(fileName: String) {
        val files = DebugLogger.getLogFiles()
        val fileToExport = files.find { it.name == fileName }
        if (fileToExport != null) {
            exportLogFile(fileToExport)
        } else {
            Toast.makeText(this, "Log file does not exist", Toast.LENGTH_SHORT).show()
        }
    }

    private fun exportLogFile(fileToExport: File) {
        if (fileToExport.exists() && fileToExport.length() > 0) {
            val uri = FileProvider.getUriForFile(
                this,
                "${applicationContext.packageName}.debug.provider",
                fileToExport
            )

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            startActivity(Intent.createChooser(intent, "Share Log File"))
        } else {
            Toast.makeText(this, "Log file is empty or does not exist", Toast.LENGTH_SHORT).show()
        }
    }
}
