[versions]
junit-jupiter = "5.10.2"
junit-platform = "1.10.2"
kotlinx-serialization = "1.12.0-RC"
kotlinx-serialization-plugin = "2.4.20"
agp = "9.4.1"
room = "3.0.2"
sakshi = "1.0.0-beta.7"
kotlin = "2.4.20"
coroutines = "1.11.0"
media3 = "1.11.0"
androidx-core = "1.19.0"
ksp = "2.3.12"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }

# Room
room-runtime = { group = "androidx.room3", name = "room3-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room3", name = "room3-compiler", version.ref = "room" }

# Sakshi SDK
sakshi-sdk = { group = "io.github.rajnishkmehta.sakshi", name = "sakshi-sdk", version.ref = "sakshi" }

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "coroutines" }

# Media3
androidx-media3-inspector-frame = { group = "androidx.media3", name = "media3-inspector-frame", version.ref = "media3" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinx-serialization-plugin" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room3", version.ref = "room" }
